### ISSUE TITLE
pytspack install failing in tests

### ISSUE THREAD

**Issue by zmoon** [noaa-oar-arl/monetio#74]
<details><summary>Message:</summary>

```
        from numpy.distutils.core import Extension
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-g_s7wkmo/setup.py", line 1, in <module>
          from numpy.distutils.core import Extension
        File "/home/runner/micromamba/envs/monetio-dev/lib/python3.8/site-packages/numpy/distutils/core.py", line 24, in <module>
          from numpy.distutils.command import config, config_compiler, \
        File "/home/runner/micromamba/envs/monetio-dev/lib/python3.8/site-packages/numpy/distutils/command/config.py", line 19, in <module>
          from numpy.distutils.mingw32ccompiler import generate_manifest
        File "/home/runner/micromamba/envs/monetio-dev/lib/python3.8/site-packages/numpy/distutils/mingw32ccompiler.py", line 28, in <module>
          from distutils.msvccompiler import get_build_version as get_build_msvc_version
      ModuleNotFoundError: No module named 'distutils.msvccompiler'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```
</details>

Should try, from [the NumPy suggestion](https://numpy.org/devdocs/reference/distutils_status_migration.html), "`SETUPTOOLS_USE_DISTUTILS=stdlib` to avoid the backwards incompatible changes in setuptools," (or downgrade before running those tests) but also probably add a pyproject.toml build requirement for pytspack.

In the last scheduled run 7 days ago it was working, with setuptools 63.4.2. Today's failed run had setuptools 65.0.0. We can see [here](https://setuptools.pypa.io/en/latest/history.html#v65-0-0) that the 65.0.0 release "removed 'msvccompiler' and 'msvc9compiler' modules from distutils".

**Comment by zmoon** [comment]
Fixed in `develop`
